---
# tasks file for rpi-k8s
- name: Run pre install best practice
  import_tasks: update.yml

- name: installing container runtime
  import_role: 
    name: rpi-install-container-runtime

- name: installing kubeadm
  import_role: 
    name: rpi-install-kubeadm
