---
# tasks file for rpi-k8s
- name: Run pre install best practice
  import_tasks: update.yml

- name: Installing the runtime
  import_role: 
    name: rpi-install-container-runtime
  vars:
    - runtime: "{{ container_runtime }}"

- name: Installing kubeadm
  import_role: 
    name: rpi-install-kubeadm
