---
# tasks file for rpi-k8s
- name: Run pre install best practice
  import_tasks: update.yml

# TODO: enable selection of the runtime
- name: Installing the runtime
  import_role: 
    name: rpi-install-container-runtime

- name: Installing kubeadm
  import_role: 
    name: rpi-install-kubeadm